<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>ResilientCheckout.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11" />
    <PackageReference Include="coverlet.collector" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ResilientCheckout\ResilientCheckout.Api.csproj" />
    <ProjectReference Include="..\ResilientCheckout.Application\ResilientCheckout.Application.csproj" />
    <ProjectReference Include="..\ResilientCheckout.Domain\ResilientCheckout.Domain.csproj" />
    <ProjectReference Include="..\ResilientCheckout.Infraestructure\ResilientCheckout.Infraestructure.csproj" />
  </ItemGroup>

</Project>
