// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResilientCheckout.Infraestructure.Persistence;

#nullable disable

namespace ResilientCheckout.Infraestructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904054747_InitialIdempotency")]
    partial class InitialIdempotency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("ResilientCheckout.Domain.Idempotency.IdempotencyRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.ToTable("IdempotencyRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
